Repository ironcore-dev/lifecycle-manager, pull requests merged in 2024-03, with the labels that each got.

#28 commit check action
  .github/workflows/pipeline.yaml
  Makefile
  config/crd/bases/lifecycle.ironcore.dev_machines.yaml
  config/crd/bases/lifecycle.ironcore.dev_machinetypes.yaml
Labels: chore, size/L

#29 Feature/reuse compliance
  .github/workflows/reuse.yml
  .reuse/dep5
  LICENSES/Apache-2.0.txt
Labels: size/L, feature

#30 Add reuse compliance status badge
  README.md
Labels: documentation, size/XS, feature

#31 readme badges
  README.md
Labels: documentation, chore, size/XS
